import { type ClassValue, clsx } from "clsx";
import { twMerge } from "tailwind-merge";

// ============= Styling Utilities =============

/**
 * Merge Tailwind CSS classes with proper precedence
 * Combines clsx for conditional classes with twMerge for precedence
 * Generated by shadcn
 */
export function cn(...inputs: ClassValue[]): string {
    return twMerge(clsx(inputs));
}

// ============= Image Utilities =============

/**
 * Check if a string is a valid base64 encoded image
 * Supports: PNG, JPEG, GIF, WebP
 */
export function isBase64Image(imageData: string): boolean {
    const base64Regex = /^data:image\/(png|jpe?g|gif|webp);base64,/;
    return base64Regex.test(imageData);
}

/**
 * Validate image file type
 */
export function isValidImageType(mimeType: string): boolean {
    const validTypes = [
        "image/png",
        "image/jpeg",
        "image/jpg",
        "image/gif",
        "image/webp",
    ];
    return validTypes.includes(mimeType);
}

// ============= Date Utilities =============

/**
 * Format a date string into a readable format
 * Returns: "HH:MM - MMM DD, YYYY"
 * Example: "2:30 PM - Feb 28, 2026"
 */
export function formatDateString(dateString: string): string {
    try {
        const date = new Date(dateString);

        const dateOptions: Intl.DateTimeFormatOptions = {
            year: "numeric",
            month: "short",
            day: "numeric",
        };

        // Use 'en-US' locale for consistent formatting between server and client
        const formattedDate = date.toLocaleDateString("en-US", dateOptions);

        const timeOptions: Intl.DateTimeFormatOptions = {
            hour: "numeric",
            minute: "2-digit",
            hour12: true,
        };

        const time = date.toLocaleTimeString("en-US", timeOptions);

        return `${time} - ${formattedDate}`;
    } catch (error) {
        console.error("Error formatting date:", error);
        return dateString;
    }
}

/**
 * Format a date relative to now
 * Returns: "2 hours ago", "1 day ago", etc.
 */
export function formatDateRelative(dateString: string): string {
    try {
        const date = new Date(dateString);
        const now = new Date();
        const diffInMs = now.getTime() - date.getTime();

        const diffInSeconds = Math.floor(diffInMs / 1000);
        const diffInMinutes = Math.floor(diffInSeconds / 60);
        const diffInHours = Math.floor(diffInMinutes / 60);
        const diffInDays = Math.floor(diffInHours / 24);

        if (diffInSeconds < 60) return "just now";
        if (diffInMinutes < 60) return `${diffInMinutes}m ago`;
        if (diffInHours < 24) return `${diffInHours}h ago`;
        if (diffInDays < 7) return `${diffInDays}d ago`;

        return formatDateString(dateString);
    } catch (error) {
        console.error("Error formatting relative date:", error);
        return dateString;
    }
}

// ============= Count Utilities =============

/**
 * Format a count with proper pluralization and padding
 * Examples:
 * - 0 -> "No Threads"
 * - 1 -> "01 Thread"
 * - 5 -> "05 Threads"
 */
export function formatThreadCount(count: number): string {
    if (count === 0) {
        return "No Threads";
    }

    const threadCount = count.toString().padStart(2, "0");
    const threadWord = count === 1 ? "Thread" : "Threads";
    return `${threadCount} ${threadWord}`;
}

/**
 * Format any count with proper singular/plural handling
 */
export function formatCount(
    count: number,
    singular: string,
    plural: string
): string {
    if (count === 0) {
        return `No ${plural}`;
    }

    const word = count === 1 ? singular : plural;
    return `${count} ${word}`;
}

// ============= String Utilities =============

/**
 * Truncate a string to a maximum length with ellipsis
 */
export function truncateString(
    str: string,
    maxLength: number,
    suffix: string = "..."
): string {
    if (str.length <= maxLength) return str;
    return str.substring(0, maxLength - suffix.length) + suffix;
}

/**
 * Capitalize the first letter of a string
 */
export function capitalize(str: string): string {
    if (!str) return str;
    return str.charAt(0).toUpperCase() + str.slice(1);
}

/**
 * Convert a string to a URL-friendly slug
 */
export function slugify(str: string): string {
    return str
        .toLowerCase()
        .trim()
        .replace(/[^\w\s-]/g, "")
        .replace(/\s+/g, "-")
        .replace(/-+/g, "-");
}

// ============= Validation Utilities =============

/**
 * Check if a string is a valid email
 */
export function isValidEmail(email: string): boolean {
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    return emailRegex.test(email);
}

/**
 * Check if a string is a valid URL
 */
export function isValidUrl(url: string): boolean {
    try {
        new URL(url);
        return true;
    } catch {
        return false;
    }
}

// ============= Array Utilities =============

/**
 * Remove duplicates from an array
 */
export function removeDuplicates<T>(arr: T[]): T[] {
    return Array.from(new Set(arr));
}

/**
 * Chunk an array into smaller arrays
 */
export function chunkArray<T>(arr: T[], chunkSize: number): T[][] {
    const chunks: T[][] = [];
    for (let i = 0; i < arr.length; i += chunkSize) {
        chunks.push(arr.slice(i, i + chunkSize));
    }
    return chunks;
}

// ============= Error Utilities =============

/**
 * Extract error message from various error types
 */
export function getErrorMessage(error: unknown): string {
    if (error instanceof Error) return error.message;
    if (typeof error === "string") return error;
    return "An unexpected error occurred";
}

/**
 * Create a safe error object for logging
 */
export function createErrorLog(
    context: string,
    error: unknown,
    additionalData?: Record<string, unknown>
): Record<string, unknown> {
    return {
        context,
        message: getErrorMessage(error),
        timestamp: new Date().toISOString(),
        stack: error instanceof Error ? error.stack : undefined,
        ...additionalData,
    };
}